- name: Ensure locales present
  become: yes
  community.general.locale_gen:
    name:
      - en_US.UTF-8
      - de_DE.UTF-8
    state: present

- name: Set locale
  become: yes
  command: localectl set-locale LANG=en_US.UTF-8

- name: "Enable multilib (Part 1)"
  become: yes
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "[multilib]"
    regexp: "^\\[multilib\\]"
    insertafter: "^#\\[multilib\\]"

- name: "Enable multilib (Part 2)"
  become: yes
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "Include = /etc/pacman.d/mirrorlist"
    insertafter: "^\\[multilib\\]"
    regexp: "Include = /etc/pacman.d/mirrorlist"

- name: Enable time synchronization
  become: yes
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: yes

- name: Enable NetworkManager
  become: yes
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: yes

- name: Enable firewall
  become: yes
  ansible.builtin.systemd:
    name: ufw
    enabled: yes

- name: Set sddm configuration
  become: yes
  ansible.builtin.copy:
    src: 10_sddm_custom.conf
    dest: /etc/sddm.conf.d/
    force: true

- name: Enable display manager
  become: yes
  ansible.builtin.systemd:
    name: sddm
    enabled: yes
