- include_tasks: "packages.yml"

- name: Enable time synchronization
  become: true
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: yes

- name: Enable NetworkManager
  become: true
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: yes

- name: Enable display manager
  become: true
  ansible.builtin.systemd:
    name: sddm
    enabled: yes

